apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-set1
spec:
  generators:
  - list: 
      elements:
      - cluster: manifests
        url: https://kubernetes.default.svc  
      - cluster: wordes
        url: https://83C4F3B913D69267AC1A3C81CF079F5A.gr7.eu-central-1.eks.amazonaws.com
  template: 
    metadata:
      name: test-set
    spec:
      project: default
      source:
        repoURL: https://github.com/lucifer140/multi-cluster-argo-demo.git
        targetRevision: HEAD
        path: '{{cluster}}'                     # [ ./wordes, ./manifest ]
      destination:
        server: '{{url}}'
        namespace: default
          # syncPolicy:
          # automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          # prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          # selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          # allowEmpty: false # 
