apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset123
  namespace: argocd
spec:
  generators:
  - list: 
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc 
      - cluster: manifests-files
        url: https://3185E919B26D929BB3B99D94AC95B7AE.gr7.eu-central-1.eks.amazonaws.com
  template: 
    metadata:
      name: test-set123
    spec:
      project: default
      source:
        repoURL: https://github.com/lucifer140/multi-cluster-argo-demo.git
        targetRevision: HEAD
        path: '{{cluster}}'                     # [ ./wordes, ./manifest ]
      destination:
        server: '{{url}}'
        namespace: default
