apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://83C4F3B913D69267AC1A3C81CF079F5A.gr7.eu-central-1.eks.amazonaws.com

  project: default
  source:
    path: wordes
    repoURL: https://github.com/lucifer140/multi-cluster-argo-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
